### ISSUE TITLE
DeepBGC failed with TypeError: rsplit() takes no keyword arguments

### ISSUE THREAD

**Issue by thinkgenome** [Merck/deepbgc#25]
Part of the error log:
--------
ERROR   19/11 15:51:37   rsplit() takes no keyword arguments
Traceback (most recent call last):
  File "/mnt/volume/miniconda/3/lib/python2.7/site-packages/deepbgc/main.py", line 113, in main
    run(argv)
  File "/mnt/volume/miniconda/3/lib/python2.7/site-packages/deepbgc/main.py", line 102, in run
    args.func.run(**args_dict)
  File "/mnt/volume/miniconda/3/lib/python2.7/site-packages/deepbgc/command/pipeline.py", line 173, in run
    step.run(record)
  File "/mnt/volume/miniconda/3/lib/python2.7/site-packages/deepbgc/pipeline/annotator.py", line 36, in run
    pfam_annotator.annotate()
  File "/mnt/volume/miniconda/3/lib/python2.7/site-packages/deepbgc/pipeline/pfam.py", line 120, in annotate
    short_pfam_id = pfam_id.rsplit('.', maxsplit=1)[0]
TypeError: rsplit() takes no keyword arguments
ERROR   19/11 15:51:37   ================================================================================
ERROR   19/11 15:51:37   DeepBGC failed with TypeError: rsplit() takes no keyword arguments
ERROR   19/11 15:51:37   ================================================================================
--------

**Comment by prihoda** [comment]
Hi @thinkgenome, good catch!  I fixed it in #26.

You can install the updated version using `pip install deepbgc==0.1.15`, or if you are using Conda, please wait until version `0.1.15` appears here (can take up to a day or two): https://anaconda.org/bioconda/deepbgc/files and then install using `conda install deepbgc==0.1.15`.

This bug is only happening in Python 2.7. In general, I recommend using Python 3.6+ for DeepBGC since Python 2.7 will not be supported in the future. You can create a new `deepbgc` conda environment with Python 3.7 using `conda create -n deepbgc python=3.7 deepbgc`

**Comment by thinkgenome** [comment]
Thanks @prihoda .
