### ISSUE TITLE
Fails with deepbgc. ImportError: cannot import name 'ChainMap'

### ISSUE THREAD

**Issue by APengs494** [Merck/deepbgc#55]
I'm getting a failure to install deepbgc  using Anaconda. And Finished.
But Fails with "ImportError: cannot import name 'ChainMap' "
Is it the python version error?
my python version is 3.6
As follows：
conda create -n myenv python==3.6
source activate myenv
and I try to deepbgc --help 
(deepbgc) [xxxxx@localhost xxxx]$ deepbgc pipeline --help
Traceback (most recent call last):
  File "/home/xxxx/.conda/envs/deepbgc/bin/deepbgc", line 6, in <module>
    from deepbgc.main import main
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/deepbgc/__init__.py", line 2, in <module>
    from .pipeline import DeepBGCClassifier, DeepBGCDetector, HmmscanPfamRecordAnnotator, DeepBGCAnnotator, ProdigalProteinRecordAnnotator
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/deepbgc/pipeline/__init__.py", line 1, in <module>
    from .classifier import DeepBGCClassifier
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/deepbgc/pipeline/classifier.py", line 4, in <module>
    from deepbgc import util
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/deepbgc/util.py", line 8, in <module>
    import pandas as pd
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/__init__.py", line 121, in <module>
    from pandas.core.computation.api import eval
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/core/computation/api.py", line 3, in <module>
    from pandas.core.computation.eval import eval
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 12, in <module>
    from pandas.core.computation.engines import _engines
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/core/computation/engines.py", line 9, in <module>
    from pandas.core.computation.ops import _mathops, _reductions
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/core/computation/ops.py", line 19, in <module>
    from pandas.core.computation.scope import _DEFAULT_GLOBALS
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/core/computation/scope.py", line 17, in <module>
    from pandas.compat.chainmap import DeepChainMap
  File "/home/xxxx/.conda/envs/deepbgc/lib/python3.6/site-packages/pandas/compat/chainmap.py", line 1, in <module>
    from typing import ChainMap, MutableMapping, TypeVar, cast
ImportError: cannot import name 'ChainMap'

**Comment by APengs494** [comment]
I tried to use python3.7 version, 
but conda will always be in the ”solving environment / “ resulting in unable to install deepbgc.

**Comment by APengs494** [comment]
Yes,  python version is wrong.
Reinstall ”conda install python==3.7“

**Comment by prihoda** [comment]
Hi @APengs494 , so was this solved by installing python 3.7? Thanks

**Comment by APengs494** [comment]
> Hi @APengs494 , so was this solved by installing python 3.7? Thanks
Hi, @prihoda  But I run “deepbgc download" 
”DeepBGC failed with URLError: EOF occurred in violation of protocol (_ssl.c:1045) “

**Comment by prihoda** [comment]
Hi @APengs494 that looks like a network issue, can you try again?

**Comment by APengs494** [comment]
> Hi @APengs494 that looks like a network issue, can you try again?
My network is connected.
![image](https://user-images.githubusercontent.com/55269492/117621489-3f51a400-b1a4-11eb-9314-0581823f1f3d.png)
I tried it again, but the port was still wrong ”_ssl.c:1045"

**Comment by APengs494** [comment]
> > Hi @APengs494 that looks like a network issue, can you try again?
> > My network is connected.
> > ![image](https://user-images.githubusercontent.com/55269492/117621489-3f51a400-b1a4-11eb-9314-0581823f1f3d.png)
> > I tried it again, but the port was still wrong ”_ssl.c:1045"

Yes, it is a network issue, I tried it again and it was successful

**Comment by APengs494** [comment]
Yes,   it is a network issue, tried it again successfully
