### ISSUE TITLE
Installing deepBGC

### ISSUE THREAD

**Issue by planctoqueen** [Merck/deepbgc#56]
I am trying to install deepBGC on my pc but I'm havig some issues that I cannot solve.

I am using Python3.7.0 and conda and already added all the necessary channels. However, everytime I try to install deepBGC I get this issue:

![image](https://user-images.githubusercontent.com/60857163/118562941-92f45c80-b765-11eb-9c90-85c270fbe5b7.png)

I already try with and without forcing the deepBGC version and get the same error everytime. 

Can you please help?

Thanks!~

**Comment by prihoda** [comment]
Hi @planctoqueen can you share the full error output and also the output of `conda info` ?

**Comment by planctoqueen** [comment]
Hi @prihoda , 

thanks for the wquick answer. 

This is the full error output 
![image](https://user-images.githubusercontent.com/60857163/118622167-f494e500-b7be-11eb-9fa6-d5ffc0150c20.png)

And here the conda info:
![image](https://user-images.githubusercontent.com/60857163/118622194-feb6e380-b7be-11eb-9b2f-23a585d01bec.png)
 Thank you!

**Comment by prihoda** [comment]
Hmm, not sure what could be wrong honestly. I hope this is not a broader issue. Anyway, you should be able to install the dependencies from conda manually and then install deepbgc using pip:
```bash
conda install prodigal hmmer
pip install deepbgc
```

**Comment by alohith** [comment]
Is there an update on this? I'm having a similar issue and looks like the same error when trying 'conda install deepbgc' with and without the '-c conda-forge' flag

the solution proposed by @prihoda on May 18th 'looks' like it worked, but when i try to do the first cmd on the tutorial 'deepbgc download' i get the following:

(deepbgc) PS A:\Akshar> deepbgc download
 _____                  ____    ____   ____
 |  _ \  ___  ___ ____ | __ )  / ___) / ___)
 | | \ \/ _ \/ _ \  _ \|  _ \ | |  _ | |
 | |_/ /  __/  __/ |_) | |_) || |_| || |___
 |____/ \___|\___| ___/|____/  \____| \____)
=================|_|===== version 0.1.29 =====
INFO    05/10 14:11:46   Creating download directory: C:\Users\TRaveler\AppData\Local\deepbgc\deepbgc\data\0.1.0
INFO    05/10 14:11:46   ================================================================================
INFO    05/10 14:11:46   Checking: C:\Users\TRaveler\AppData\Local\deepbgc\deepbgc\data\0.1.0\detector\deepbgc.pkl
INFO    05/10 14:11:46   Downloading: https://github.com/Merck/deepbgc/releases/download/v0.1.0/deepbgc.pkl
ERROR   05/10 14:11:46   0
Traceback (most recent call last):
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\site-packages\deepbgc\main.py", line 113, in main
    run(argv)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\site-packages\deepbgc\main.py", line 102, in run
    args.func.run(**args_dict)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\site-packages\deepbgc\command\download.py", line 25, in run
    util.download_files(DOWNLOADS)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\site-packages\deepbgc\util.py", line 403, in download_files
    download_file(url=url, target_path=target_path, checksum=checksum, gzipped=gzipped)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\site-packages\deepbgc\util.py", line 425, in download_file
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\urllib\request.py", line 1318, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\http\client.py", line 1416, in __init__
    context = ssl._create_default_https_context()
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\ssl.py", line 589, in create_default_context
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\ssl.py", line 490, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Users\TRaveler\.conda\envs\deepbgc\lib\ssl.py", line 482, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: unknown error (_ssl.c:4034)
ERROR   05/10 14:11:46   ================================================================================
ERROR   05/10 14:11:46   DeepBGC failed with SSLError
ERROR   05/10 14:11:46   ================================================================================
ERROR   05/10 14:11:46   unknown error (_ssl.c:4034)


Also, I don't think hmmer or prodigal have actually been installed..

**Comment by alohith** [comment]
Hi @prihoda here's what it looks like. Very similar to what I was seeing before, also the same if I instead say 'python=3.6'
`(base) PS A:\Akshar> conda create -n deepbgc python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\TRaveler\.conda\envs\deepbgc

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.5.30  |       h5b45459_0         171 KB  conda-forge
    openssl-3.0.0              |       h8ffe710_1        10.0 MB  conda-forge
    pip-21.2.4                 |     pyhd8ed1ab_0         1.1 MB  conda-forge
    python-3.7.10              |h900ac77_102_cpython        17.9 MB  conda-forge
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    setuptools-58.2.0          |   py37h03978a9_0         1.0 MB  conda-forge
    sqlite-3.36.0              |       h8ffe710_2         1.2 MB  conda-forge
    ucrt-10.0.20348.0          |       h57928b3_0         1.2 MB  conda-forge
    vc-14.2                    |       hb210afc_5          13 KB  conda-forge
    vs2015_runtime-14.29.30037 |       h902a5da_5         1.3 MB  conda-forge
    wheel-0.37.0               |     pyhd8ed1ab_1          31 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        33.9 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2021.5.30-h5b45459_0
  openssl            conda-forge/win-64::openssl-3.0.0-h8ffe710_1
  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.7.10-h900ac77_102_cpython
  python_abi         conda-forge/win-64::python_abi-3.7-2_cp37m
  setuptools         conda-forge/win-64::setuptools-58.2.0-py37h03978a9_0
  sqlite             conda-forge/win-64::sqlite-3.36.0-h8ffe710_2
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
Proceed ([y]/n)? y


Downloading and Extracting Packages
python_abi-3.7       | 4 KB      | ############################################################################ | 100%
ucrt-10.0.20348.0    | 1.2 MB    | ############################################################################ | 100%
openssl-3.0.0        | 10.0 MB   | ############################################################################ | 100%
python-3.7.10        | 17.9 MB   | ############################################################################ | 100%
sqlite-3.36.0        | 1.2 MB    | ############################################################################ | 100%
ca-certificates-2021 | 171 KB    | ############################################################################ | 100%
pip-21.2.4           | 1.1 MB    | ############################################################################ | 100%
wheel-0.37.0         | 31 KB     | ############################################################################ | 100%
vc-14.2              | 13 KB     | ############################################################################ | 100%
setuptools-58.2.0    | 1.0 MB    | ############################################################################ | 100%
vs2015_runtime-14.29 | 1.3 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate deepbgc
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS A:\Akshar> conda activate deepbgc
(deepbgc) PS A:\Akshar> conda install deepbgc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

(deepbgc) PS A:\Akshar>`

**Comment by planctoqueen** [comment]
Hi! 

I don't know if this is the correct solution but what solve the problem for me was to remove the conda-forge channel. conda config --remove channels conda-forge

hope it helps!~

**Comment by Christabelteh** [comment]
I have tried to run commands in anaconda powershell with conda create -n deepbgc python=3.7 hmmer prodigal,  conda activate deepbgc and pip install deepbgc and seems hmmer and prodigal have been successfully downloaded . I have attached the output of following commands.
conda create -n deepbgc python=3.7 hmmer prodigal output:
![Screenshot (2776)](https://user-images.githubusercontent.com/132284748/235482696-344e2bd2-d695-4cdf-a2b4-165338ebe4af.png)
pip install deepbgc output:
![Screenshot (2779)](https://user-images.githubusercontent.com/132284748/235483100-685d7e32-e546-4204-b71a-04a88d7a8df3.png)
end...:
![Screenshot (2780)](https://user-images.githubusercontent.com/132284748/235483264-60ad6f39-0c64-4f94-b9c3-e878f688a80a.png)
However, every time I run the command conda install deepbgc, it keep showing me this issue:  
![Screenshot (2774)](https://user-images.githubusercontent.com/132284748/235480722-7fb81778-3e0c-4a07-a72e-1886d0aa741d.png)
Btw, this is the info of my conda:
![Screenshot (2782)](https://user-images.githubusercontent.com/132284748/235485728-d8259e45-513b-4b03-8d33-47ef3e66995e.png)

Could somebody help me to solve the issue, your help would greatly appreciated for me. Thank you.
