### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by esraagithub** [Merck/deepbgc#84]
hello
 I used this step to install deepbgc but t get error at the end

Set up Bioconda and Conda-Forge channels:

conda config --add channels bioconda
conda config --add channels conda-forge
Install DeepBGC using:

# Create a separate DeepBGC environment and install dependencies
conda create -n deepbgc python=3.7 hmmer prodigal

# Install DeepBGC into the environment using pip
conda activate deepbgc
pip install deepbgc

**error message** 
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 113, in main
    run(argv)
  File "/root/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/main.py", line 102, in run
    args.func.run(**args_dict)
  File "/root/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/command/pipeline.py", line 133, in run
    min_bio_domains=min_bio_domains
  File "/root/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/pipeline/detector.py", line 35, in __init__
    self.model = SequenceModelWrapper.load(model_path)
  File "/root/miniconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/models/wrapper.py", line 188, in load
    raise ValueError("Error unpickling model from path '{}'".format(path), e)
ValueError: ("Error unpickling model from path '/root/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl'", TypeError('Descriptors cannot not be created directly.\nIf this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\nIf you cannot immediately regenerate your protos, some other possible workarounds are:\n 1. Downgrade the protobuf package to 3.20.x or lower.\n 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\n\nMore information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates'))
ERROR   20/11 16:30:10   ================================================================================
ERROR   20/11 16:30:10   DeepBGC failed with ValueError: Error unpickling model from path '/root/.local/share/deepbgc/data/0.1.0/detector/deepbgc.pkl'
ERROR   20/11 16:30:10   ================================================================================
ERROR   20/11 16:30:10   Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
ERROR   20/11 16:30:10   ================================================================================

**Comment by esraagithub** [comment]
this error still exists
