### ISSUE TITLE
ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by chengyou96** [Merck/deepbgc#95]
Hi there,

Thanks for developing Deepbgc! It seems that I successfully installed DeepBGC version 0.1.31 on my Macbook. However, when I checked deepbgc info, there is an error. Could you provide any suggestions on this matter?

(deepbgc) cynthiayo@ DeepBGC % conda install deepbgc==0.1.31          
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

## Package Plan ##

  environment location: /opt/anaconda3/envs/deepbgc

  added / updated specs:
    - deepbgc==0.1.31

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    biopython-1.79             |   py37h69ee0a8_2         2.6 MB  conda-forge
    deepbgc-0.1.31             |     pyhca03a8a_0          48 KB  bioconda
    libprotobuf-3.15.8         |       hcf210ce_1         2.2 MB  conda-forge
    openssl-1.1.1w             |       h8a1eda9_0         1.7 MB  conda-forge
    protobuf-3.15.8            |   py37hd8d24ac_0         323 KB  conda-forge
    python-3.7.12              |haf480d7_100_cpython        24.3 MB  conda-forge
    sigtool-0.1.3              |       h57ddcff_0         209 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.4 MB

The following packages will be REMOVED:

  grpc-cpp-1.48.1-h966d1d5_1

The following packages will be UPDATED:

  biopython                             1.76-py37h0b31af3_0 --> 1.79-py37h69ee0a8_2
  deepbgc                               0.1.27-pyhdfd78af_0 --> 0.1.31-pyhca03a8a_0

The following packages will be SUPERSEDED by a higher-priority channel:

  grpcio             conda-forge::grpcio-1.48.1-py37hed26b~ --> pkgs/main::grpcio-1.42.0-py37ha29bfda_0

The following packages will be DOWNGRADED:

  libprotobuf                             3.21.8-hbc0c0cd_0 --> 3.15.8-hcf210ce_1
  openssl                                  3.2.0-hd75f5a5_1 --> 1.1.1w-h8a1eda9_0
  protobuf                            4.21.8-py37hac51a3e_0 --> 3.15.8-py37hd8d24ac_0
  python                        3.7.12-hf3644f1_100_cpython --> 3.7.12-haf480d7_100_cpython
  sigtool                                  0.1.3-h88f4db0_0 --> 0.1.3-h57ddcff_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
libprotobuf-3.15.8   | 2.2 MB    | ########################################################################## | 100% 
deepbgc-0.1.31       | 48 KB     | ########################################################################## | 100% 
openssl-1.1.1w       | 1.7 MB    | ########################################################################## | 100% 
biopython-1.79       | 2.6 MB    | ########################################################################## | 100% 
python-3.7.12        | 24.3 MB   | ########################################################################## | 100% 
sigtool-0.1.3        | 209 KB    | ########################################################################## | 100% 
protobuf-3.15.8      | 323 KB    | ########################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
(deepbgc) cynthiayo@ DeepBGC % deepbgc info
Traceback (most recent call last):
  File "/opt/anaconda3/envs/deepbgc/bin/deepbgc", line 6, in <module>
    from deepbgc.main import main
  File "/opt/anaconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/__init__.py", line 2, in <module>
    from .pipeline import DeepBGCClassifier, DeepBGCDetector, HmmscanPfamRecordAnnotator, DeepBGCAnnotator, ProdigalProteinRecordAnnotator
  File "/opt/anaconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/pipeline/__init__.py", line 1, in <module>
    from .classifier import DeepBGCClassifier
  File "/opt/anaconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/pipeline/classifier.py", line 4, in <module>
    from deepbgc import util
  File "/opt/anaconda3/envs/deepbgc/lib/python3.7/site-packages/deepbgc/util.py", line 8, in <module>
    import pandas as pd
  File "/opt/anaconda3/envs/deepbgc/lib/python3.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

**Comment by chengyou96** [comment]
This error occurred because I tried to install on Mac.
